# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\x1a\x1bgoogle/protobuf/empty.proto\"\\\n\nUserConfig\x12\x11\n\tthread_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\tchat_mode\x18\x03 \x01(\t\x12\x17\n\x0frecursion_limit\x18\x04 \x01(\x05\"I\n\x0b\x43hatRequest\x12\x12\n\nuser_input\x18\x01 \x01(\t\x12&\n\x0buser_config\x18\x02 \x01(\x0b\x32\x11.agent.UserConfig\"Z\n\x0c\x43hatResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x13\n\x0btoken_usage\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t\"W\n\x0bStreamChunk\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x16\n\x0e\x66inal_response\x18\x02 \x01(\x08\x12\r\n\x05token\x18\x03 \x01(\x05\x12\x11\n\tnode_name\x18\x04 \x01(\t\"8\n\x0eHistoryRequest\x12&\n\x0buser_config\x18\x01 \x01(\x0b\x32\x11.agent.UserConfig\"r\n\x0fHistoryResponse\x12\x34\n\x13latest_conversation\x18\x01 \x03(\x0b\x32\x17.agent.ConversationPair\x12\x18\n\x10\x63umulative_usage\x18\x02 \x01(\x05\x12\x0f\n\x07summary\x18\x03 \x01(\t\"D\n\x10\x43onversationPair\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"3\n\rCancelRequest\x12\x11\n\tthread_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"2\n\x0e\x43\x61ncelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\nServerInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x10\n\x08run_time\x18\x02 \x01(\t2\xb7\x02\n\x0c\x41gentService\x12/\n\x04\x43hat\x12\x12.agent.ChatRequest\x1a\x13.agent.ChatResponse\x12\x36\n\nChatStream\x12\x12.agent.ChatRequest\x1a\x12.agent.StreamChunk0\x01\x12G\n\x16GetConversationHistory\x12\x15.agent.HistoryRequest\x1a\x16.agent.HistoryResponse\x12\x39\n\nCancelTask\x12\x14.agent.CancelRequest\x1a\x15.agent.CancelResponse\x12:\n\rGetServerInfo\x12\x16.google.protobuf.Empty\x1a\x11.agent.ServerInfoB\x18Z\x16proto/agent;agent_grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026proto/agent;agent_grpc'
  _globals['_USERCONFIG']._serialized_start=51
  _globals['_USERCONFIG']._serialized_end=143
  _globals['_CHATREQUEST']._serialized_start=145
  _globals['_CHATREQUEST']._serialized_end=218
  _globals['_CHATRESPONSE']._serialized_start=220
  _globals['_CHATRESPONSE']._serialized_end=310
  _globals['_STREAMCHUNK']._serialized_start=312
  _globals['_STREAMCHUNK']._serialized_end=399
  _globals['_HISTORYREQUEST']._serialized_start=401
  _globals['_HISTORYREQUEST']._serialized_end=457
  _globals['_HISTORYRESPONSE']._serialized_start=459
  _globals['_HISTORYRESPONSE']._serialized_end=573
  _globals['_CONVERSATIONPAIR']._serialized_start=575
  _globals['_CONVERSATIONPAIR']._serialized_end=643
  _globals['_CANCELREQUEST']._serialized_start=645
  _globals['_CANCELREQUEST']._serialized_end=696
  _globals['_CANCELRESPONSE']._serialized_start=698
  _globals['_CANCELRESPONSE']._serialized_end=748
  _globals['_SERVERINFO']._serialized_start=750
  _globals['_SERVERINFO']._serialized_end=797
  _globals['_AGENTSERVICE']._serialized_start=800
  _globals['_AGENTSERVICE']._serialized_end=1111
# @@protoc_insertion_point(module_scope)
