// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: agent.proto

package agent_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户配置
type UserConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ThreadId       string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`                    // 会话线程ID
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                          // 用户ID
	ChatMode       string                 `protobuf:"bytes,3,opt,name=chat_mode,json=chatMode,proto3" json:"chat_mode,omitempty"`                    // 聊天模式: "stream" 或 "normal"
	RecursionLimit int32                  `protobuf:"varint,4,opt,name=recursion_limit,json=recursionLimit,proto3" json:"recursion_limit,omitempty"` // 递归限制
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserConfig) Reset() {
	*x = UserConfig{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConfig) ProtoMessage() {}

func (x *UserConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConfig.ProtoReflect.Descriptor instead.
func (*UserConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *UserConfig) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *UserConfig) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserConfig) GetChatMode() string {
	if x != nil {
		return x.ChatMode
	}
	return ""
}

func (x *UserConfig) GetRecursionLimit() int32 {
	if x != nil {
		return x.RecursionLimit
	}
	return 0
}

// 对话请求
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInput     string                 `protobuf:"bytes,1,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"`    // 用户输入
	UserConfig    *UserConfig            `protobuf:"bytes,2,opt,name=user_config,json=userConfig,proto3" json:"user_config,omitempty"` // 用户配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

func (x *ChatRequest) GetUserConfig() *UserConfig {
	if x != nil {
		return x.UserConfig
	}
	return nil
}

// 对话响应（非流式）
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`                                   // Agent回复
	TokenUsage    int32                  `protobuf:"varint,2,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`      // Token使用量
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`                              // 是否成功
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 错误信息（如果有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ChatResponse) GetTokenUsage() int32 {
	if x != nil {
		return x.TokenUsage
	}
	return 0
}

func (x *ChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChatResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 流式输出块
type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`                                     // 输出内容
	FinalResponse bool                   `protobuf:"varint,2,opt,name=final_response,json=finalResponse,proto3" json:"final_response,omitempty"` // 是否为最终响应
	Token         int32                  `protobuf:"varint,3,opt,name=token,proto3" json:"token,omitempty"`                                      // Token使用量
	NodeName      string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`                 // 当前节点名称（用于状态提示）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StreamChunk) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *StreamChunk) GetFinalResponse() bool {
	if x != nil {
		return x.FinalResponse
	}
	return false
}

func (x *StreamChunk) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *StreamChunk) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

// 历史记录请求
type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserConfig    *UserConfig            `protobuf:"bytes,1,opt,name=user_config,json=userConfig,proto3" json:"user_config,omitempty"` // 用户配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HistoryRequest) GetUserConfig() *UserConfig {
	if x != nil {
		return x.UserConfig
	}
	return nil
}

// 历史记录响应
type HistoryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LatestConversation []*ConversationPair    `protobuf:"bytes,1,rep,name=latest_conversation,json=latestConversation,proto3" json:"latest_conversation,omitempty"` // 最新对话对
	CumulativeUsage    int32                  `protobuf:"varint,2,opt,name=cumulative_usage,json=cumulativeUsage,proto3" json:"cumulative_usage,omitempty"`         // 累计Token使用量
	Summary            string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`                                                 // 对话摘要
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HistoryResponse) GetLatestConversation() []*ConversationPair {
	if x != nil {
		return x.LatestConversation
	}
	return nil
}

func (x *HistoryResponse) GetCumulativeUsage() int32 {
	if x != nil {
		return x.CumulativeUsage
	}
	return 0
}

func (x *HistoryResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// 对话对（用户消息和AI回复）
type ConversationPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`            // "user" 或 "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`      // 消息内容
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationPair) Reset() {
	*x = ConversationPair{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationPair) ProtoMessage() {}

func (x *ConversationPair) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationPair.ProtoReflect.Descriptor instead.
func (*ConversationPair) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ConversationPair) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationPair) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConversationPair) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 取消任务请求
type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"` // 要取消的线程ID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *CancelRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *CancelRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 取消任务响应
type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功取消
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 服务器信息
type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // 服务器版本
	StartTime     string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	RunTime       string                 `protobuf:"bytes,3,opt,name=run_time,json=runTime,proto3" json:"run_time,omitempty"` // 构建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ServerInfo) GetRunTime() string {
	if x != nil {
		return x.RunTime
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\x1a\x1bgoogle/protobuf/empty.proto\"\x88\x01\n" +
	"\n" +
	"UserConfig\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tchat_mode\x18\x03 \x01(\tR\bchatMode\x12'\n" +
	"\x0frecursion_limit\x18\x04 \x01(\x05R\x0erecursionLimit\"`\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"user_input\x18\x01 \x01(\tR\tuserInput\x122\n" +
	"\vuser_config\x18\x02 \x01(\v2\x11.agent.UserConfigR\n" +
	"userConfig\"\x84\x01\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x1f\n" +
	"\vtoken_usage\x18\x02 \x01(\x05R\n" +
	"tokenUsage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x7f\n" +
	"\vStreamChunk\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12%\n" +
	"\x0efinal_response\x18\x02 \x01(\bR\rfinalResponse\x12\x14\n" +
	"\x05token\x18\x03 \x01(\x05R\x05token\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\"D\n" +
	"\x0eHistoryRequest\x122\n" +
	"\vuser_config\x18\x01 \x01(\v2\x11.agent.UserConfigR\n" +
	"userConfig\"\xa0\x01\n" +
	"\x0fHistoryResponse\x12H\n" +
	"\x13latest_conversation\x18\x01 \x03(\v2\x17.agent.ConversationPairR\x12latestConversation\x12)\n" +
	"\x10cumulative_usage\x18\x02 \x01(\x05R\x0fcumulativeUsage\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"^\n" +
	"\x10ConversationPair\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"E\n" +
	"\rCancelRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"D\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\n" +
	"ServerInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\brun_time\x18\x03 \x01(\tR\arunTime2\xb7\x02\n" +
	"\fAgentService\x12/\n" +
	"\x04Chat\x12\x12.agent.ChatRequest\x1a\x13.agent.ChatResponse\x126\n" +
	"\n" +
	"ChatStream\x12\x12.agent.ChatRequest\x1a\x12.agent.StreamChunk0\x01\x12G\n" +
	"\x16GetConversationHistory\x12\x15.agent.HistoryRequest\x1a\x16.agent.HistoryResponse\x129\n" +
	"\n" +
	"CancelTask\x12\x14.agent.CancelRequest\x1a\x15.agent.CancelResponse\x12:\n" +
	"\rGetServerInfo\x12\x16.google.protobuf.Empty\x1a\x11.agent.ServerInfoB\x18Z\x16proto/agent;agent_grpcb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agent_proto_goTypes = []any{
	(*UserConfig)(nil),       // 0: agent.UserConfig
	(*ChatRequest)(nil),      // 1: agent.ChatRequest
	(*ChatResponse)(nil),     // 2: agent.ChatResponse
	(*StreamChunk)(nil),      // 3: agent.StreamChunk
	(*HistoryRequest)(nil),   // 4: agent.HistoryRequest
	(*HistoryResponse)(nil),  // 5: agent.HistoryResponse
	(*ConversationPair)(nil), // 6: agent.ConversationPair
	(*CancelRequest)(nil),    // 7: agent.CancelRequest
	(*CancelResponse)(nil),   // 8: agent.CancelResponse
	(*ServerInfo)(nil),       // 9: agent.ServerInfo
	(*emptypb.Empty)(nil),    // 10: google.protobuf.Empty
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: agent.ChatRequest.user_config:type_name -> agent.UserConfig
	0,  // 1: agent.HistoryRequest.user_config:type_name -> agent.UserConfig
	6,  // 2: agent.HistoryResponse.latest_conversation:type_name -> agent.ConversationPair
	1,  // 3: agent.AgentService.Chat:input_type -> agent.ChatRequest
	1,  // 4: agent.AgentService.ChatStream:input_type -> agent.ChatRequest
	4,  // 5: agent.AgentService.GetConversationHistory:input_type -> agent.HistoryRequest
	7,  // 6: agent.AgentService.CancelTask:input_type -> agent.CancelRequest
	10, // 7: agent.AgentService.GetServerInfo:input_type -> google.protobuf.Empty
	2,  // 8: agent.AgentService.Chat:output_type -> agent.ChatResponse
	3,  // 9: agent.AgentService.ChatStream:output_type -> agent.StreamChunk
	5,  // 10: agent.AgentService.GetConversationHistory:output_type -> agent.HistoryResponse
	8,  // 11: agent.AgentService.CancelTask:output_type -> agent.CancelResponse
	9,  // 12: agent.AgentService.GetServerInfo:output_type -> agent.ServerInfo
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
